/*
 * Lista completa e estática dos países do mundo (nomes em português).
 * Optámos por não depender de uma API externa (ex.: restcountries.com)
 * porque em produção essas chamadas falharam por CORS/indisponibilidade.
 */
export const PAISES: string[] = [
  "Afeganistão",
  "África do Sul",
  "Albânia",
  "Alemanha",
  "Andorra",
  "Angola",
  "Antígua e Barbuda",
  "Arábia Saudita",
  "Argélia",
  "Argentina",
  "Arménia",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Bahrein",
  "Bélgica",
  "Belize",
  "Benim",
  "Bielorrússia",
  "Bolívia",
  "Bósnia e Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunei",
  "Bulgária",
  "Burquina Faso",
  "Burundi",
  "Butão",
  "Cabo Verde",
  "Camarões",
  "Camboja",
  "Canadá",
  "Catar",
  "Cazaquistão",
  "Chade",
  "Chile",
  "China",
  "Chipre",
  "Colômbia",
  "Comores",
  "Congo",
  "Coreia do Norte",
  "Coreia do Sul",
  "Costa do Marfim",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Dinamarca",
  "Djibuti",
  "Dominica",
  "Egito",
  "El Salvador",
  "Emirados Árabes Unidos",
  "Equador",
  "Eritreia",
  "Eslováquia",
  "Eslovénia",
  "Espanha",
  "Estados Unidos",
  "Estónia",
  "Etiópia",
  "Fiji",
  "Filipinas",
  "Finlândia",
  "França",
  "Gabão",
  "Gâmbia",
  "Gana",
  "Geórgia",
  "Granada",
  "Grécia",
  "Guatemala",
  "Guiana",
  "Guiné",
  "Guiné-Bissau",
  "Guiné Equatorial",
  "Haiti",
  "Honduras",
  "Hungria",
  "Iémen",
  "Ilhas Marshall",
  "Ilhas Salomão",
  "Índia",
  "Indonésia",
  "Irão",
  "Iraque",
  "Irlanda",
  "Islândia",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jordânia",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letónia",
  "Líbano",
  "Libéria",
  "Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Macedónia do Norte",
  "Madagáscar",
  "Malásia",
  "Malawi",
  "Maldivas",
  "Mali",
  "Malta",
  "Marrocos",
  "Maurícia",
  "Mauritânia",
  "México",
  "Micronésia",
  "Moçambique",
  "Moldávia",
  "Mónaco",
  "Mongólia",
  "Montenegro",
  "Myanmar",
  "Namíbia",
  "Nauru",
  "Nepal",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Noruega",
  "Nova Zelândia",
  "Omã",
  "Países Baixos",
  "Palau",
  "Palestina",
  "Panamá",
  "Papua-Nova Guiné",
  "Paquistão",
  "Paraguai",
  "Peru",
  "Polónia",
  "Portugal",
  "Quénia",
  "Quirguistão",
  "Reino Unido",
  "República Centro-Africana",
  "República Checa",
  "República Democrática do Congo",
  "República Dominicana",
  "Roménia",
  "Ruanda",
  "Rússia",
  "Samoa",
  "Santa Lúcia",
  "São Cristóvão e Neves",
  "São Marino",
  "São Tomé e Príncipe",
  "São Vicente e Granadinas",
  "Seicheles",
  "Senegal",
  "Serra Leoa",
  "Sérvia",
  "Singapura",
  "Síria",
  "Somália",
  "Sri Lanka",
  "Suazilândia",
  "Sudão",
  "Sudão do Sul",
  "Suécia",
  "Suíça",
  "Suriname",
  "Tailândia",
  "Taiwan",
  "Tajiquistão",
  "Tanzânia",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trindade e Tobago",
  "Tunísia",
  "Turcomenistão",
  "Turquia",
  "Tuvalu",
  "Ucrânia",
  "Uganda",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Vaticano",
  "Venezuela",
  "Vietname",
  "Zâmbia",
  "Zimbabué",
];
